name: "Cookidoo Today"
description: "Pobiera plan przepisów z Cookidoo (dzień + tydzień) i scrapuje obrazki."
version: "0.1.0"
slug: "cookidoo_today"
url: "https://github.com/TWOJ_LOGIN/cookidoo-ha-addons"
arch:
  - aarch64
  - amd64

init: false
startup: application
boot: auto

ingress: true
ingress_port: 8099
panel_icon: "mdi:chef-hat"

ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Cookidoo Today API"

options:
  email: ""
  password: ""
  country: "pl"
  refresh_minutes: 15

schema:
  email: str
  password: password
  country: str
  refresh_minutes: int(1, 1440)
